version: '3'

services:
    jenkins: 
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            - DOTNET_CLI_TELEMETRY_OPTOUT=1
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
            - "./keys:/var/ssh_keys:"
volumes:
    jenkins_home:

