version: '3'

services:
    jenkins: 
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            - DOTNET_CLI_TELEMETRY_OPTOUT=1
        ports:
            - "8080:8080"
            - "50000:50000"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.morcegao_site_dev.rule=Host(`jenkins.guergolet.com.br`)"
            - "traefik.http.routers.morcegao_site_dev.entrypoints=web,websecure"
            - "traefik.http.routers.morcegao_site_dev.tls=true" 
            - "traefik.http.routers.morcegao_site_dev.tls.certresolver=letsencrypt"            
        volumes:
            - jenkins_home:/var/jenkins_home
            - "./keys:/jenkins:ro"
volumes:
    jenkins_home:

